CREATE TABLE User (
   IdUser INT PRIMARY KEY AUTO_INCREMENT,
   name VARCHAR(255),
   addresses VARCHAR(255),
   FlooNetworkID VARCHAR(50),
   mail VARCHAR(100),
   timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
